In [1]:
import pandas as pd
import numpy as np 

np.random.seed(26)
cantidad_pedidos = 500

fechas_despacho = pd.to_datetime('2025-08-01') + pd.to_timedelta(np.random.randint(0, 60, cantidad_pedidos), unit = 'D')
fechas_llegada = fechas_despacho + pd.to_timedelta(np.random.randint(2, 25, cantidad_pedidos), unit = 'D')

datos_bodega = {
    'ID_Remito': np.arange(8000, 8000 + cantidad_pedidos),
    'Varietal': np.random.choice(['Malbec', 'Cabernet Franc', 'Chardonnay', 'Syrah'], cantidad_pedidos),
    'Cajas_Enviadas': np.random.randint(10, 200, cantidad_pedidos),
    'Precio_Por_Caja': np.random.randint(15000, 45000, cantidad_pedidos),
    'Fecha_Despacho': fechas_despacho.astype(str),
    'Fecha_Llegada': fechas_llegada.astype(str)
}

df_bodega = pd.DataFrame(datos_bodega)
df_bodega.to_csv('logistica_bodega.csv', index=False)
print('✅ Archivo logistica_bodega.csv generado exitosamente.')

✅ Archivo logistica_bodega.csv generado exitosamente.

In [3]:
#Ejercicio 2
df = pd.read_csv('logistica_bodega.csv')
df['Valor_Total_Envio'] = df['Cajas_Enviadas'] * df['Precio_Por_Caja']

df.head(3)

,ID_Remito,Varietal,Cajas_Enviadas,Precio_Por_Caja,Fecha_Despacho,Fecha_Llegada,Valor_Total_Envio
0,8000,Malbec,133,33311,2025-09-23,2025-10-06,4430363
1,8001,Cabernet Franc,199,23451,2025-08-07,2025-08-09,4666749
2,8002,Chardonnay,162,23261,2025-09-18,2025-10-12,3768282

In [ ]:
#Ejercicio 3
# Convertir columnas de texto a datetime
df['Fecha_Despacho'] = pd.to_datetime(df['Fecha_Despacho'])
df['Fecha_Llegada'] = pd.to_datetime(df['Fecha_Llegada'])

# Calcular diferencia y extraer solo los días enteros
df['Dias_En_Transito'] = (df['Fecha_Llegada'] - df['Fecha_Despacho']).dt.days

print("Fechas convertidas y columna 'Dias_En_Transito' creada.")

✅ Fechas convertidas y columna 'Dias_En_Transito' creada.

In [ ]:
#Ejercicio 4
def evaluar_calidad_logistica(dias):
    if dias <= 7:
        return 'Optimo'
    elif 8 <= dias <= 15:
        return 'Aceptable'
    else: 
        return 'Riesgo de temperatura'

df['Estado_Calidad'] = df['Dias_En_Transito'].apply(evaluar_calidad_logistica)

print("Distribución del Estado de Calidad:")
display (df['Estado_Calidad'].value_counts())

Distribución del Estado de Calidad:

Estado_Calidad
Riesgo de temperatura    194
Aceptable                180
Optimo                   126
Name: count, dtype: int64

In [8]:
#Ejercicio 5
mascara = (df['Varietal']== 'Malbec') & (df['Estado_Calidad']== 'Riesgo de Temperatura')

df_malbec_riesgo = df[mascara].copy()

print("Envio de malbec en riesgo de temperatura: ")
display(df_malbec_riesgo)

total_en_riesgo = df_malbec_riesgo['Valor_Total_Envio'].sum()
print(f"\n Total en malbec en riesgo por demoras logisticas: ${total_en_riesgo:,.2f}")

Envio de malbec en riesgo de temperatura:

Empty DataFrame
Columns: [ID_Remito, Varietal, Cajas_Enviadas, Precio_Por_Caja, Fecha_Despacho, Fecha_Llegada, Valor_Total_Envio, Dias_En_Transito, Estado_Calidad]
Index: []

 Total en malbec en riesgo por demoras logisticas: $0.00