In [1]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError
from IPython.display import display

# Credenciales por defecto de PostgreSQL local
usuario = 'postgres'
password = 'postgres' # ⚠️ Pon la que usaste al instalar PostgreSQL
host = 'localhost'
puerto = '5432' # Puerto por defecto de PostgreSQL
base_de_datos = 'logistica_cuyo_db'

# URI de conexión para PostgreSQL
uri_conexion = f"postgresql+psycopg2://{usuario}:{password}@{host}:{puerto}/{base_de_datos}"

try:
    engine = create_engine(uri_conexion)
    with engine.connect() as conexion:
        print("Conexión exitosa al servidor PostgreSQL")
except SQLAlchemyError as e:
    print(f"Error al conectar con el servidor: {e}")

Conexión exitosa al servidor PostgreSQL

In [2]:
query_pendientes = """
    SELECT * 
    FROM envios 
    WHERE Estado_Entrega = 'Pendiente';
"""

# 6. Ejecutar la consulta y guardar en df_pendientes
df_pendientes = pd.read_sql_query(query_pendientes, engine)

# 7. Mostrar el DataFrame en pantalla
print("--- Pedidos que faltan despachar (Pendientes) ---")
display(df_pendientes)

--- Pedidos que faltan despachar (Pendientes) ---

   id_pedido fecha_envio      barrio  valor_ars estado_entrega
0          3  2026-06-01  Guaymallen    5100.75      Pendiente
1          9  2026-06-03       Maipu    7300.00      Pendiente
2         14  2026-06-04   Las Heras    2900.50      Pendiente

In [3]:
query_reporte = """
    SELECT 
        Barrio,
        SUM(Valor_ARS) AS Recaudacion_Total,
        COUNT(*) AS Volumen_Pedidos
    FROM envios
    GROUP BY Barrio
    ORDER BY Recaudacion_Total DESC;
"""

# 11. Ejecutar la consulta y guardar en df_reporte
df_reporte = pd.read_sql_query(query_reporte, engine)

# Verificamos que se haya cargado correctamente antes de formatear
print("--- Reporte de recaudación por zona (Sin formato) ---")
display(df_reporte.head())

--- Reporte de recaudación por zona (Sin formato) ---

          barrio  recaudacion_total  volumen_pedidos
0     Godoy Cruz           17701.00                4
1  Lujan de Cuyo           17600.00                2
2          Maipu           14000.00                2
3         Ciudad           10900.00                3
4     Guaymallen            9900.75                2

In [4]:
df_reporte_ejecutivo = df_reporte.style.format({
    'Recaudacion_Total': '${:,.2f}'
})

# Muestren el resultado final en pantalla
print("--- Reporte Ejecutivo Final ---")
display(df_reporte_ejecutivo)

--- Reporte Ejecutivo Final ---